### ISSUE TITLE
搜尋動畫時程式顯示「抱歉，搜尋過程中出現了未知錯誤 」

### ISSUE THREAD

**Issue by zelda0079** [icelam/anime1-downloader#23]
[05/May/2023:01:22:42 +0800]	INFO	開始搜尋與「在無神世界裡進行傳教活動」相關的動畫
[05/May/2023:01:22:42 +0800]	ERROR	搜尋過程中出現了未知錯誤 (除錯訊息：error='NoneType' object has no attribute 'find_all', type(error)=<class 'AttributeError'>, traceback=Traceback (most recent call last):\n  File "cli\downloader.py", line 142, in search_anime\n  File "cli\scraper.py", line 17, in get_search_result\n  File "cli\scraper.py", line 30, in extract_search_results\nAttributeError: 'NoneType' object has no attribute 'find_all')
[05/May/2023:01:22:45 +0800]	INFO	已載入 config.ini: {'max_parallel_download': '3', 'video_directory': 'video'}
[05/May/2023:01:22:58 +0800]	INFO	開始搜尋與「為美好的世界獻上爆焰」相關的動畫
[05/May/2023:01:22:58 +0800]	ERROR	搜尋過程中出現了未知錯誤 (除錯訊息：error='NoneType' object has no attribute 'find_all', type(error)=<class 'AttributeError'>, traceback=Traceback (most recent call last):\n  File "cli\downloader.py", line 142, in search_anime\n  File "cli\scraper.py", line 17, in get_search_result\n  File "cli\scraper.py", line 30, in extract_search_results\nAttributeError: 'NoneType' object has no attribute 'find_all')

結果是不能搜索

**Comment by icelam** [comment]
您好，非常感謝您一直使用我製作的小程式。

由於最近Anime1.me新增了 Cloudflare 「我不是機械人」的驗證程序，導致程式無法運作。除非Anime1.me能提供不需要驗證的 API，否則這個問題並無任何解決方案。

這個小程式原本只是為了練習 Python 而製作出來，沒想到能夠長期被使用，作為開發者，我覺得有些高興。但現在這種情況下，只能選擇停止維護。

我會在這個 repository 的 readme加上結束維護的語句，但如果有任何人能夠提供解決方法，我也非常歡迎 pull request。

再次感謝你的使用。

**Comment by zelda0079** [comment]
> 您好，非常感謝您一直使用我製作的小程式。
> 
> 由於最近Anime1.me新增了 Cloudflare 「我不是機械人」的驗證程序，導致程式無法運作。除非Anime1.me能提供不需要驗證的 API，否則這個問題並無任何解決方案。
> 
> 這個小程式原本只是為了練習 Python 而製作出來，沒想到能夠長期被使用，作為開發者，我覺得有些高興。但現在這種情況下，只能選擇停止維護。
> 
> 我會在這個 repository 的 readme加上結束維護的語句，但如果有任何人能夠提供解決方法，我也非常歡迎 pull request。
> 
> 再次感謝你的使用。

ANIME1好像移除了Cloudflare 
又可以用了
